[package]
name = "rustie"
version = "0.1.2"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross Platform Shell"
repository = "https://github.com/sigmaSd/rustie"
license = "MIT"

[dependencies]
crossterm = "0.9.6"
